name: safe_qr_app
description: "Safe QR App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  shared_preferences: ^2.3.2
  equatable: ^2.0.7
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  mobile_scanner: ^5.0.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true